name: Kwiki-Indexer
version: 0.1.1
abstract: Kwiki Indexer class.
author: Russell Heilling <chewtoy@s8n.net
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  Kwiki: 0.32
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
